services:
  - type: web
    name: credgerly
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_default_categories
    startCommand: gunicorn finance_project.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: credgerly.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: credgerly-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false

databases:
  - name: credgerly-db
    plan: free
    databaseName: credgerly
    user: credgerly_user

